config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :carreras
  
  resources :alumnos do
      resources :carreras
end

   root 'alumnos#index'

end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
	has_many :carreras, dependent: :destroy
	validates_presence_of :Nombre
	validates_presence_of :Apellido_Paterno
	validates_presence_of :Apellido_Materno
	validates_presence_of :Fecha_De_Nacimiento
	validates_presence_of :Sexo
	validates_presence_of :Categoria
	belongs_to :user
end

app/models/carrera.rb
class Carrera < ActiveRecord::Base
	belongs_to :alumno
	validates_presence_of :alumno_id
	validates_presence_of :Carrera
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable,  :validatable
          has_many :alumnos
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]
  #other before_actions
  before_action :authenticate_user!

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = current_user.alumnos.all
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = current_user.alumnos.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = current_user.alumnos.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: 'Alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = current_user.alumnos.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_params
      params.require(:alumno).permit(:Nombre, :Apellido_Paterno, :Apellido_Materno, :Fecha_De_Nacimiento, :Sexo, :Categoria)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carreras_controller.rb
class CarrerasController < ApplicationController
  before_action :set_carrera, only: [:show, :edit, :update, :destroy]

  # GET /carreras
  # GET /carreras.json
  def index
    @carreras = Carrera.all
  end

  # GET /carreras/1
  # GET /carreras/1.json
  def show
  end

  # GET /carreras/new
  def new
    @carrera = Carrera.new
  end

  # GET /carreras/1/edit
  def edit
  end

  # POST /carreras
  # POST /carreras.json
  def create
    @carrera = Carrera.new(carrera_params)

    respond_to do |format|
      if @carrera.save
        format.html { redirect_to @carrera, notice: 'Carrera was successfully created.' }
        format.json { render :show, status: :created, location: @carrera }
      else
        format.html { render :new }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carreras/1
  # PATCH/PUT /carreras/1.json
  def update
    respond_to do |format|
      if @carrera.update(carrera_params)
        format.html { redirect_to @carrera, notice: 'Carrera was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrera }
      else
        format.html { render :edit }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carreras/1
  # DELETE /carreras/1.json
  def destroy
    @carrera.destroy
    respond_to do |format|
      format.html { redirect_to carreras_url, notice: 'Carrera was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrera
      @carrera = Carrera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrera_params
      params.require(:carrera).permit(:alumno_id, :Carrera)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/views/alumnos/_form.html.erb
<%= form_for(@alumno) do |f| %>
  <% if @alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% @alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Apellido_Paterno %><br>
    <%= f.text_field :Apellido_Paterno %>
  </div>
  <div class="field">
    <%= f.label :Apellido_Materno %><br>
    <%= f.text_field :Apellido_Materno %>
  </div>
  <div class="field">
    <%= f.label :Fecha_De_Nacimiento %><br>
    <%= f.date_select :Fecha_De_Nacimiento, start_year: 1960, last_year: 2020 %>
  </div>
  <div class="field">

    <% sexos ={
      'Masculino' => 'M',
      'Femenino' => 'F',
    }
    %>
    <%= f.label :Sexo %><br>
    <%= f.select :Sexo,sexos %>
  </div>
  <div class="field">

    <% categorias ={
      'Tiempo Completo' => 'tiempo_completo',
      'Medio Tiempo' => 'medio_tiempo',
      'Educación a Distancia' => 'educacion_a_distancia',
    } 
    %>
    <%= f.label :Categoria %><br>
    <%= f.select :Categoria, categorias %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alumnos/edit.html.erb
<h1>Editing Alumno</h1>

<%= render 'form' %>

<%= link_to 'Show', @alumno %> |
<%= link_to 'Back', alumnos_path %>

app/views/alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alumnos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido paterno</th>
      <th>Apellido materno</th>
      <th>Fecha de nacimiento</th>
      <th>Sexo</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
      <tr>
        <td><%= alumno.Nombre %></td>
        <td><%= alumno.Apellido_Paterno %></td>
        <td><%= alumno.Apellido_Materno %></td>
        <td><%= alumno.Fecha_De_Nacimiento %></td>
        <td><%= alumno.Sexo %></td>
        <td><%= alumno.Categoria %></td>
        <td><%= link_to 'Show', alumno %></td>
        <td><%= link_to 'Edit', edit_alumno_path(alumno) %></td>
        <td><%= link_to 'Destroy', alumno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumno', new_alumno_path %>

app/views/alumnos/new.html.erb
<h1>New Alumno</h1>

<%= render 'form' %>

<%= link_to 'Back', alumnos_path %>

app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @alumno.Nombre %>
</p>

<p>
  <strong>Apellido paterno:</strong>
  <%= @alumno.Apellido_Paterno %>
</p>

<p>
  <strong>Apellido materno:</strong>
  <%= @alumno.Apellido_Materno %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @alumno.Fecha_De_Nacimiento %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @alumno.Sexo %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @alumno.Categoria %>
</p>

<%= link_to 'Edit', edit_alumno_path(@alumno) %> |
<%= link_to 'Back', alumnos_path %>

app/views/carreras/_form.html.erb
<%= form_for(@carrera) do |f| %>
  <% if @carrera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carrera.errors.count, "error") %> prohibited this carrera from being saved:</h2>

      <ul>
      <% @carrera.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alumno_id %><br>
    <%= f.number_field :alumno_id %>
  </div>
  <div class="field">
   
   <% carreras ={
    'Derecho' => 'derecho',
    'Mecatrónica' => 'mecatronica',
    'Informática' => 'informatica',
    'Turismo' => 'turismo',
   }
   %>
    <%= f.label :Carrera %><br>
    <%= f.select :Carrera, carreras %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carreras/edit.html.erb
<h1>Editing Carrera</h1>

<%= render 'form' %>

<%= link_to 'Show', @carrera %> |
<%= link_to 'Back', carreras_path %>

app/views/carreras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carreras</h1>

<table>
  <thead>
    <tr>
      <th>Alumno</th>
      <th>Carrera</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carreras.each do |carrera| %>
      <tr>
        <td><%= carrera.alumno_id %></td>
        <td><%= carrera.Carrera %></td>
        <td><%= link_to 'Show', carrera %></td>
        <td><%= link_to 'Edit', edit_carrera_path(carrera) %></td>
        <td><%= link_to 'Destroy', carrera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrera', new_carrera_path %>

app/views/carreras/new.html.erb
<h1>New Carrera</h1>

<%= render 'form' %>

<%= link_to 'Back', carreras_path %>

app/views/carreras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alumno:</strong>
  <%= @carrera.alumno_id %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @carrera.Carrera %>
</p>

<%= link_to 'Edit', edit_carrera_path(@carrera) %> |
<%= link_to 'Back', carreras_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>